### ISSUE TITLE
Add a --version flag to fossil

### ISSUE THREAD

**Issue by dburkart** [dburkart/fossil#118]
It would be nice to know the version of a given standalone fossil binary.

I'm thinking we can use https://pkg.go.dev/embed to build this into the CI build process.

**Comment by gideonw** [comment]
There is also a build flag method that lets you set the value of a variable 

main.go
```
var version string
```
I didn't look up the actual flag, but it is something like the following
```
go build -ldflag "main.version=v1.0.0"
```
