### ISSUE TITLE
Schema Support

### ISSUE THREAD

**Issue by dburkart** [dburkart/fossil#17]
See [the overview document](./docs/overview.md) for a primer on schema syntax. Supporting schemas (and hence data predicates) will involve the following:

  1. A parser for schema syntax
  2. A data-packing protocol that can pack data based on a given schema definition
  3. Data predicate support in the query language that can interact with packed data

**Comment by dburkart** [comment]
Grammar for schemas:

```abnf
schema = type / array / shallow-map

type = "string" / "boolean" / "int8" / "int16" / "int32" / "int64" / "float"
array = "[" 1*DIGIT "]" type

shallow-map = "{" map-entries "}"
map-entries = 1*map-entry
map-entry = key ":" map-value ","
map-value = type / array

key = DQUOTE 1*( ALPHA / DIGIT / "_" / "-" ) DQUOTE
```

**Comment by dburkart** [comment]
Grammar adjusted a bit to the following:
```abnf
schema      = type / array / shallow-map

type        = "string" / "binary" / fixed-type		  
fixed-type  = "boolean" / "int8" / "int16" / "int32" / "int64" /
              "uint8" / "uint16" / "uint32" / "uint64" / "float32" / "float64"
array       = "[" 1*DIGIT "]" fixed-type

shallow-map = "{" map-entries "}"
map-entries = 1*map-entry
map-entry   = key ":" map-value ","
map-value   = type / array

key         = DQUOTE 1*( ALPHA / DIGIT / "_" / "-" ) DQUOTE
```

Changes:
  * Allow for "binary" type
  * Disallow variable-length types in arrays

**Comment by gideonw** [comment]
A note, the fixed-type specifies `"float32" / "float64"` right now we only support a generic `float` type.

**Comment by dburkart** [comment]
Yeah I'm wondering if we only need float64

**Comment by dburkart** [comment]
Then again I can think of applications for 32 bit floats, so I'll probably fix.

**Comment by dburkart** [comment]
I've renamed "shallow map" to "composite".
