### ISSUE TITLE
Remove fossil test subcommand

### ISSUE THREAD

**Issue by dburkart** [dburkart/fossil#22]
Since we improved the protocol to allow for two-way communication, using `fossil test` causes a running server to spam the following message over and over:

```
2022-11-28T13:51:25-08:00 ERR pkg/server/mux.go:102 > error reading from the conn error="read tcp4 127.0.0.1:8001->127.0.0.1:56458: read: connection reset by peer"
```

We should handle connection resets better in the server, and also update the `test` command to be well-behaved.

**Comment by gideonw** [comment]
I don't think so. I did update it to spam data, but it definitely is an early project command we should probably nix. Unless we want it to serve a function like test config or connection. Like a health check command or something
