### ISSUE TITLE
Propogate query syntax errors back to the client

### ISSUE THREAD

**Issue by dburkart** [dburkart/fossil#43]
Today, query syntax errors die in the parser, since we respond to all panics in `query.Parse()` by simply printing out the message. Instead, let's propagate the error back out to the caller so database clients know there was a syntax error (instead of just seeing "No Results")

**Comment by gideonw** [comment]
This is going to require a lot of tuple return value updates :D (x, error)

**Comment by dburkart** [comment]
> This is going to require a lot of tuple return value updates :D (x, error)

I think I have found a way for this to be not too many tuples :)
